///< err: file err msg
///< !------------------------------------------------------------
#define AMSG_FileErr_FileUpdateFail             "更新数据表失败"
#define AMSG_FileErr_FileNotExist               "文件不存在"
#define AMSG_FileErr_RecordNotFound             "记录未找到"
#define AMSG_FileErr_FileMoveFail               "删除文件失败"
#define AMSG_FileErr_FileCloseFail              "关闭文件失败"
#define AMSG_FileErr_DeleteRecordFail           "删除文件数据失败"
#define AMSG_FileErr_ReadFileFail               "读文件失败"
#define AMSG_FileErr_WriteFileFail              "写文件失败"
#define AMSG_FileErr_CreateFileFail             "创建文件失败"
#define AMSG_FileErr_OpenFileFail               "打开文件失败"
#define AMSG_FileErr_FileReadWriteErr           "文件读写错"

///< err: printer err msg
///< !------------------------------------------------------------
#define AMSG_PrinterErr_GetParamFail            "获取打印机参数失败"
#define AMSG_PrinterErr_InitPrinterFail         "初始化打印机失败"
#define AMSG_PrinterErr_SetParamFail            "设置打印机参数失败"
#define AMSG_PrinterErr_ClearCacheFail          "清空打印机缓存失败"
#define AMSG_PrinterErr_CloseFail               "关闭打印机失败"
#define AMSG_PrinterErr_FeedFail                "打印机走纸错误"
#define AMSG_PrinterErr_GetFontDataFail         "打印文字失败"
#define AMSG_PrinterErr_GetBitmapDataFail       "打印图片失败"
#define AMSG_PrinterErr_PrintTxtOver            "打印文字超限"
#define AMSG_PrinterErr_PrintQRFail             "打印条码或二维码失败"
#define AMSG_PrinterErr_PrintFail               "打印失败"
#define AMSG_PrinterErr_NoPaper                 "打印机缺纸,请装纸"
#define AMSG_PrinterErr_Overheat                "打印机过热,请稍后重试"
#define AMSG_PrinterErr_ParamError              "打印机参数错误"
#define AMSG_PrinterErr_CommunicationError      "打印机通讯错误"
#define AMSG_PrinterErr_NoPrinterModule         "无打印机模块"
#define AMSG_PrinterErr_LowBattery              "电池电量低,请及时充电"
#define AMSG_PrinterErr_NotFontFile             "打印机字库丢失"
#define AMSG_PrinterErr_CacheFull               "打印机缓存不足"
#define AMSG_PrinterErr_Printing                "正在打印"
#define AMSG_PrinterErr_PlzInstallBattery       "请安装电池后,请重试"
#define AMSG_PrinterErr_PrinterFailure          "打印机故障,请重试"

///< err: cashier err msg
///< !------------------------------------------------------------
#define AMSG_CashierErr_DeleteNotAllow          "不允许删除"
#define AMSG_CashierErr_EnterPwdNotSame         "两次输入密码不一致"
#define AMSG_CashierErr_ChangeNotAllow          "不允许修改"
#define AMSG_CashierErr_ChangeFail              "修改失败"
#define AMSG_CashierErr_CashierIllegal          "操作员不符"
#define AMSG_CashierErr_CashierFull             "操作员已存满"
#define AMSG_CashierErr_CashierNotExist         "操作员不存在"
#define AMSG_CashierErr_CashierExist            "操作员已存在"
#define AMSG_CashierErr_OtherErr                "操作员错误"

///< err:
///< !------------------------------------------------------------
#define AMSG_Err_End                            "交易结束"
#define AMSG_Err_Cancel                         "交易取消"
#define AMSG_Err_Timeout                        "操作超时"
#define AMSG_Err_ParamErr                       "参数错误"
#define AMSG_Err_DriverErr                      "驱动错误"
#define AMSG_Err_MfDriverErr                    "非接读卡模块错误"
#define AMSG_Err_IccDriverErr                   "IC卡读卡模块错误"
#define AMSG_Err_ScanDriverErr                  "扫码模块错误"
#define AMSG_Err_MagneticTrackDriverErr         "磁轨读卡模块错误"
#define AMSG_Err_PrinterDriverErr               "打印机故障,请重试"
#define AMSG_Err_CommuErr                       "通讯错"
#define AMSG_Err_ServerReturnErr                "主机返回错"
#define AMSG_Err_CommuParamErr                  "通讯参数错"
#define AMSG_Err_NetworkConnectFail             "网络连接失败"
#define AMSG_Err_DataSendFail                   "数据发送失败"
#define AMSG_Err_DataReceiveFail                "数据接收失败"
#define AMSG_Err_KeyStoreFail                   "密钥存储失败"
#define AMSG_Err_KeyDataErr                     "密钥数据错"
#define AMSG_Err_EncryptionFail                 "加密失败"
#define AMSG_Err_MACCheckErr                    "MAC校验错"
#define AMSG_Err_CacheOverflow                  "缓存超限"
#define AMSG_Err_InvalidData                    "无效数据"
#define AMSG_Err_LoadDataErr                    "数据加载错"
#define AMSG_Err_ParsingDataErr                 "数据解析错"
#define AMSG_Err_AttestationErr                 "验签错误"
#define AMSG_Err_NotLogon                       "未签到,请先签到"
#define AMSG_Err_PleaseSettlement               "请先结算"
#define AMSG_Err_AdminNotTrade                  "主管不能交易,请先签到"
#define AMSG_Err_BatchMismatch                  "批次不符,请重新签到"
#define AMSG_Err_WorkKeyErr                     "密钥错误,请重新签到"
#define AMSG_Err_TradeFull                      "交易已满,请结算"
#define AMSG_Err_TradeEmpty                     "无交易记录"
#define AMSG_Err_OriginalTradeNotExist          "原交易不存在"
#define AMSG_Err_OriginalTradeVoid              "原交易已撤销或不支持"
#define AMSG_Err_LastTradeNotPrinted            "上笔交易未正常打印,请重打"
#define AMSG_Err_AmountOverlimit                "金额超限"
#define AMSG_Err_CardNOInconsistent             "退款卡号不一致"
#define AMSG_Err_WrongPassword                  "密码错误"
#define AMSG_Err_TradeHasBlocked                "该交易已屏蔽,请重新选择"
#define AMSG_Err_BitCheckErr                    "域校验出错"
#define AMSG_Err_IllFormattedData               "输入格式错误,请重新输入"
#define AMSG_Err_MsgTypeNotMatch                "消息类型不匹配"
#define AMSG_Err_AmountNotMatch                 "交易金额不匹配"
#define AMSG_Err_SerialNoNotMatch               "流水号不匹配"
#define AMSG_Err_TID_NotMatch                   "终端号不匹配"
#define AMSG_Err_MID_NotMatch                   "商户号不匹配"
#define AMSG_Err_IllFormattedSignatureData      "签名格式错,请重新签名"
#define AMSG_Err_KeyCheckErr                    "密钥校验错"
#define AMSG_Err_InsufficientStorageSpace       "存储空间不足,请先结算"
#define AMSG_Err_NotSettled                     "终端未结算过"
#define AMSG_Err_UnknownErr                     "未知错误"

///< err: server error message
///< !------------------------------------------------------------
#define AMSG_HostErr_Approval                   "交易成功"
#define AMSG_HostErr_ReferToIssuer              "交易失败,请联系发卡行"
#define AMSG_HostErr_InvalidCardNO              "无效卡号"
#define AMSG_HostErr_InvalidMerchant            "商户未登记"
#define AMSG_HostErr_Retry                      "交易失败,请重试"
#define AMSG_HostErr_AmountExceedsLimit         "交易金额超限"
#define AMSG_HostErr_ExpiredCard                "该卡已过期"
#define AMSG_HostErr_CardholderAuthenticationFailed   "持卡人认证失败"
#define AMSG_HostErr_PartialApprovedAmount      "显示部分批准金额,提示操作员"
#define AMSG_HostErr_Successful                 "成功,此为VIP客户"
#define AMSG_HostErr_InvalidTrade               "无效交易"
#define AMSG_HostErr_InvalidAmount              "无效金额"
#define AMSG_HostErr_NoCardIssuer               "此卡无对应发卡方"
#define AMSG_HostErr_CardNotInitialized         "该卡未初始化或睡眠卡"
#define AMSG_HostErr_IncorrectOperation         "操作有误或超出交易允许天数"
#define AMSG_HostErr_NoOriginalDeal             "没有原始交易,请联系发卡方"
#define AMSG_HostErr_PlzTryAgain                "请重试"
#define AMSG_HostErr_CardNotAccepted            "此卡不能受理"
#define AMSG_HostErr_CardSomethingWrong         "此卡有误,请换卡重试"
#define AMSG_HostErr_PlzUseChip                 "请使用芯片,如损坏请联系发卡行"
#define AMSG_HostErr_InsufficientBalance        "可用余额不足"
#define AMSG_HostErr_IncorrectPIN               "密码错"
#define AMSG_HostErr_BannedDeals                "发卡方禁止该卡在本机进行此交易"
#define AMSG_HostErr_CardCheckError             "卡片校验错"
#define AMSG_HostErr_AmountMismatch             "交易金额与原交易不匹配"
#define AMSG_HostErr_TradeNotSupported          "发卡方不支持的交易"
#define AMSG_HostErr_TakeLostCard               "挂失卡"
#define AMSG_HostErr_CheatCard                  "作弊卡,吞卡"
#define AMSG_HostErr_TakeStolenCard             "被窃卡"
#define AMSG_HostErr_RestrictedCard             "受限制的卡"
#define AMSG_HostErr_SaleBeyondLimit            "超出消费次数限制"
#define AMSG_HostErr_ConfiscateCardContactAcquirer  "没收卡,请联系收单行"
#define AMSG_HostErr_CardTradeNotAllowed        "不允许此卡交易"
#define AMSG_HostErr_ConfiscateCard             "没收卡"
#define AMSG_HostErr_TimeoutRetry               "交易超时,请重试"
#define AMSG_HostErr_ContactAcquirer            "交易失败,请联系收单行或银联"
#define AMSG_HostErr_PinRetryOver               "密码错误次数超限"
#define AMSG_HostErr_PlzLogon                   "请向网络中心签到"
#define AMSG_HostErr_TransFail                  "交易失败"
#define AMSG_HostErr_DuplicateBatch             "POS终端重传脱机数据"
#define AMSG_HostErr_TryAgainLater              "交易失败,请稍后重试"
#define AMSG_HostErr_SystemBatch                "系统日切,请稍后重试"
#define AMSG_HostErr_CardIssuingStateAnomaly    "发卡方状态不正常,请稍后重试"
#define AMSG_HostErr_CardIssuingLineAnomaly     "发卡方线路异常,请稍后重试"
#define AMSG_HostErr_RepeatDeal                 "拒绝,重复交易,请稍后重试"
#define AMSG_HostErr_SystemError                "拒绝,系统出错"
#define AMSG_HostErr_CenterAnomaly              "拒绝,交换中心异常,请稍后重试"
#define AMSG_HostErr_InvalidTerminal            "终端号未登记"
#define AMSG_HostErr_CardIssuerTimeout          "发卡方超时"
#define AMSG_HostErr_IllFormattedPin            "PIN格式错,请重新签到"
#define AMSG_HostErr_MacError                   "MAC校验错,请重新签到"
#define AMSG_HostErr_TransferCurrencyNotAgree   "转账货币不一致"
#define AMSG_HostErr_ToAccountBankIncorrect     "资金到账行账号不正确"
#define AMSG_HostErr_ConfirmBankReceivedFunds   "交易成功,请向资金到账行确认"
#define AMSG_HostErr_SecurityHandlingFailed     "安全处理失败"
#define AMSG_HostErr_TradeError                 "交易出错"

///< Message
///< !------------------------------------------------------------
#define AMSG_FuncParamErr               "传参错误"
#define AMSG_SetSuccess                 "设置成功"
#define AMSG_SetFailed                  "设置失败"
#define AMSG_EnterToSet                 "按[确认]继续设置"
#define AMSG_CancelToExit               "按[取消]退出设置"
#define AMSG_QuerySuccess               "查询成功"
#define AMSG_DownloadSuccess            "下载成功"
#define AMSG_ChangeSuccess              "修改成功"
#define AMSG_DelSuccess                 "删除成功"
#define AMSG_AddSuccess                 "添加成功"
#define AMSG_ResetSuccess               "重置成功"
#define AMSG_EnterOrCancel              "[确认]            [取消]"
#define AMSG_CancelExit                 "[取消]退出"
#if defined(QR200)
#define AMSG_PageTurn                   "[0/.]翻页"
#else
#define AMSG_PageTurn                   "[↑↓]翻页"
#endif
#define AMSG_EnterPowerOff              "1.关机"
#define AMSG_ClearReboot                "2.重启"
#define AMSG_CancelBack                 "3.返回"
#define AMSG_Rebooting                  "正在重启..."
#define AMSG_PowerOff                   "正在关机..."

///< title
///< !------------------------------------------------------------
#define AMSG_Title_Headline             "中国银联"
#define AMSG_Title_Logon                "签到"
#define AMSG_Title_Logoff               "签退"
#define AMSG_Title_Settlement           "结算"
#define AMSG_Title_LoadAID              "IC卡参数下载"
#define AMSG_Title_LoadCAPK             "IC卡公钥下载"
#define AMSG_Title_LoadRF               "终端业务控制参数"
#define AMSG_Title_Reversal             "正在冲正"
#define AMSG_Title_Upload               "正在上送脚本结果"
#define AMSG_Title_QueryBal             "余额查询"
#define AMSG_Title_Sale                 "消费"
#define AMSG_Title_SaleVoid             "撤销"
#define AMSG_Title_CardSaleVoid         "银行卡撤销"
#define AMSG_Title_ScanSaleVoid         "扫码付撤销"
#define AMSG_Title_Refund               "退货"
#define AMSG_Title_CardRefund           "银行卡退货"
#define AMSG_Title_ScanRefund           "扫码付退货"
#define AMSG_Title_Print                "打印"
#define AMSG_Title_ReprintLastTrade     "重打最后一笔"
#define AMSG_Title_ReprintAnyTrade      "重打任意一笔"
#define AMSG_Title_PrintTradeDetail     "打印交易明细"
#define AMSG_Title_PrintTradeTotal      "打印交易汇总"
#define AMSG_Title_ReprintSettleSheet   "重打结算单"
#define AMSG_Title_Manage               "管理"
#define AMSG_Title_TradeInquiries       "交易查询"
#define AMSG_Title_ViewTradeDetail      "查询交易明细"
#define AMSG_Title_ViewTradeTotal       "查询交易汇总"
#define AMSG_Title_VoucherNoSearch      "按凭证号查询"
#define AMSG_Title_CashiersManage       "柜员管理"
#define AMSG_Title_ChangeAdminPwd       "主管改密"
#define AMSG_Title_CashierAdd           "增加柜员"
#define AMSG_Title_CashierQuery         "查询柜员"
#define AMSG_Title_CashierDel           "删除柜员"
#define AMSG_Title_CashierChangePwd     "柜员改密"
#define AMSG_Title_PosLogon             "POS签到"
#define AMSG_Title_CashierLogon         "操作员签到"
#define AMSG_Title_SysManage            "系统管理"

///< secretKey.c
///< !------------------------------------------------------------
#define AMSG_SetTMKIndex                "主密钥索引设置"
#define AMSG_SecretKeyManage            "终端密钥管理"
#define AMSG_DownloadTMK                "主密钥灌装"
#define AMSG_DownloadTMK_IC             "IC卡灌装"
#define AMSG_DownloadTMK_POS            "母POS灌装"
#define AMSG_DownloadTMK_Manual         "手输密钥"
#define AMSG_SerialPortRecv             "[串口]等待接收..."
#define AMSG_DownloadTMKSuccess         "主密钥灌装成功"
#define AMSG_DownloadTMKFail            "主密钥灌装失败"
#define AMSG_USE_TMK_INDEX              "当前主密钥索引(1-9):"
#define AMSG_SetSecretKeyType           "设置密钥DES算法"
#define AMSG_SecretKeySingle            "单倍长"
#define AMSG_SecretKeyDouble            "双倍长"
#define AMSG_SecretKeyDoubleTDK         "双倍长(磁道加密)"
#define AMSG_PlzPushSecretKeyCard       "请插密钥卡"
#define AMSG_DontMoveSecretKeyCard      "请勿移卡"
#define AMSG_SecretKeyCardReadFailed    "读密钥卡失败"
#define AMSG_ManualSecretKey            "主密钥灌装(手输)"
#define AMSG_InputTMKIndex              "请输入主密钥索引号(1-9):"
#define AMSG_InputTMK                   "请输入主密钥(%d位)"

///< elesign.c
///< !------------------------------------------------------------
#define AMSG_EsignInputSign             "请持卡人在屏幕方框内签名"

///< cashier.c
///< !------------------------------------------------------------
#define AMSG_CashierSearch              "查询操作员"
#define AMSG_AddCashierNo               "增加操作员"
#define AMSG_DelCashierNo               "删除操作员"
#define AMSG_CashierNo                  "操作员号:"
#define AMSG_ResetAdminPwd              "重置主管密码"
#define AMSG_IsResetAdminPwd            "是否重置主管密码?"
#define AMSG_ChangeSafePwd              "修改安全密码"
#define AMSG_ChangeManagePwd            "修改管理员密码"
#define AMSG_ChangeAdminPwd             "修改主管密码"
#define AMSG_ChangeCashierNoPwd         "修改操作员密码"
#define AMSG_InputCashierNo             "请输入操作员号:"
#define AMSG_InputCashierNoPwd          "请输入操作员密码:"
#define AMSG_InputAdminPwd              "请输入主管密码:"
#define AMSG_InputManagePwd             "请输入管理员密码:"
#define AMSG_InputSafePwd               "请输入安全密码:"

#define AMSG_InputOldPwd                "请输入原密码:"
#define AMSG_InputNewPwd                "请输入新密码:"
#define AMSG_InputAgain                 "请再输入一次:"

///< trans.c
///< !------------------------------------------------------------
#define AMSG_Success                    "成功"
#define AMSG_PlzConfirm                 "请确认"
#define AMSG_Approval                   "交易成功"
#define AMSG_Welcome                    "欢迎使用"
#define AMSG_NotLogon                   " 未签到 "
#define AMSG_InputAmount                "请输入金额:"
#define AMSG_ScanVoucherNo              "请扫付款凭证号"
#define AMSG_VoidSuccess                "撤销成功"
#define AMSG_RefundSuccess              "退货成功"
#define AMSG_SettlementSuccess          "结算成功"

///< trans_online.c
///< !------------------------------------------------------------
#define AMSG_ConnectingHost             "正在连接网络"
#define AMSG_HostConnected              "已连接数据中心"
#define AMSG_SendingData                "发送数据中"
#define AMSG_ReceivingData              "正在接收数据"
#define AMSG_Processing                 "正在处理"
#define AMSG_PleaseWait                 "请稍等..."
#define AMSG_Received                   "接收完成"
#define AMSG_DownloadSearch             "联机查询中"
#define AMSG_Downloading                "正在下载"
#define AMSG_DownloadEnd                "下载结束"
#define AMSG_ReverseNumSend             "第%d次冲正"
#define AMSG_ReverseSuccess             "冲正成功"
#define AMSG_ReverseFailed              "冲正失败,请人工处理"
#define AMSG_ScriptSend                 "第%d次上送脚本结果"
#define AMSG_UploadSuccess              "上送成功"
#define AMSG_UploadFailed               "上送失败"
#define AMSG_SettlementOK               "对帐平"
#define AMSG_SettlementUneven           "对账不平"
#define AMSG_SettlementFailed           "对账失败"

///< trans_search.c
///< !------------------------------------------------------------
#define AMSG_TotalTransactions          "交易总额"
#define AMSG_DebitInternalCard          "借记:(内卡)"
#define AMSG_DebitForeignCard           "借记:(外卡)"
#define AMSG_CreditInternalCard         "贷记:(内卡)"
#define AMSG_CreditForeignCard          "贷记:(外卡)"
#define AMSG_TickCount                  "%d笔"
#define AMSG_Amount                     "%ld.%02ld元"

///< trans_ui.c
///< !------------------------------------------------------------
#define AMSG_InputErrClearKey           "输错请按[清除键]"
#define AMSG_ChangeIM                   "[字母键]切换输入法"
#define AMSG_Warnings                   "警 告"
#define AMSG_BatteryLow                 "电池电量低"
#define AMSG_BatteryTooLow              "电池电量过低,禁止交易"
#define AMSG_InCharge                   "充电中..."
#define AMSG_PlzConnectCharger          "请连接充电器"
#define AMSG_PlzChargeInTime            "请及时充电,按[确认]继续"
#define AMSG_PlzPlugInBattery           "请插入电池"
#define AMSG_PlzPulloutCard             "请拔卡"
#define AMSG_InputCardNo                "请输入卡号:"
#define AMSG_HandCardNo                 "手输卡号"
#define AMSG_ScanCode                   "扫码"
#define AMSG_PlzAgain                   "请重新"
#define AMSG_ReadCardErr                "读卡错误"
#define AMSG_Plz                        "请"
#define AMSG_SwipeCard                  "刷卡"
#define AMSG_PlugInCard                 "插卡"
#define AMSG_TapCard                    "挥卡"
#define AMSG_ScanSale                   "扫码消费"
#define AMSG_ScanSaleVoid               "扫码撤销"
#define AMSG_ScanRefund                 "扫码退货"
#define AMSG_Revoked                    "(已撤销)"
#define AMSG_InputOriginalSerialNo      "请输入原凭证号:"
#define AMSG_PreviousRecord             "[确认]上一笔"
#define AMSG_Balance                    "可用余额:"
#define AMSG_ClearManualInput           "手输请按[清除键]"
#define AMSG_InputVoucherNo             "请输入付款凭证号:"
#define AMSG_InvalidDateFormat          "日期格式非法,请重新输入"
#define AMSG_ConfirmAmount              "请确认金额:"
#define AMSG_CancelEdit                 "按[取消]修改"
#define AMSG_UI_Msg1                    "金额:%ld.%02ld元"

///< pos_param.c
///< !------------------------------------------------------------
#define AMSG_Param_Msg1                 "商户参数设置"
#define AMSG_Param_Msg2                 "通讯参数设置"
#define AMSG_Param_Msg3                 "交易功能设置"
#define AMSG_Param_Msg4                 "终端密钥管理"
#define AMSG_Param_Msg5                 "系统参数设置"
#define AMSG_Param_Msg6                 "密码管理"
#define AMSG_Param_Msg7                 "其他功能设置"
#define AMSG_Param_Msg8                 "是否测试模式"
#define AMSG_Param_Msg9                 "电子签名设置"
#define AMSG_Param_Msg10                "1.支持%3s    0.不支持%3s"
#define AMSG_Param_Msg11                "1.是%3s    0.否%3s"
#define AMSG_Param_Msg12                "1.清除%3s    0.放弃%3s"
#define AMSG_Param_Msg13                "终端号:"
#define AMSG_Param_Msg14                "商户号:"
#define AMSG_Param_Msg15                "商户名称:"
#define AMSG_Param_Msg16                "当前流水号:"
#define AMSG_Param_Msg20                "结算是否提示打印明细"
#define AMSG_Param_Msg23                "消费撤销是否用卡"
#define AMSG_Param_Msg25                "消费撤销是否输密"
#define AMSG_Param_Msg29                "主机1 IP:"
#define AMSG_Param_Msg30                "主机1 端口:"
#define AMSG_Param_Msg31                "主机1 是否打开SSL加密"
#define AMSG_Param_Msg32                "重试次数:"
#define AMSG_Param_Msg33                "接收超时:"
#define AMSG_Param_Msg35                "余额查询"
#define AMSG_Param_Msg36                "消费"
#define AMSG_Param_Msg37                "消费撤销"
#define AMSG_Param_Msg38                "退货"
#define AMSG_Param_Msg44                "其他交易控制"
#define AMSG_Param_Msg45                "撤销/退货是否输入主管密码"
#define AMSG_Param_Msg48                "是否打开EMV日志"
#define AMSG_Param_Msg49                "打印张数设置"
#define AMSG_Param_Msg50                "打印张数设置(张)"
#define AMSG_Param_Msg51                "最大交易笔数设置"
#define AMSG_Param_Msg52                "最大交易笔数:"
#define AMSG_Param_Msg56                "消息重发次数"
#define AMSG_Param_Msg58                "最大交易笔数"
#define AMSG_Param_Msg59                "其他设置"
#define AMSG_Param_Msg61                "功能不支持!"
#define AMSG_Param_Msg62                "消息重发次数"
#define AMSG_Param_Msg63                "重试次数:"
#define AMSG_Param_Msg64                "清除冲正"
#define AMSG_Param_Msg65                "清除中..."
#define AMSG_Param_Msg66                "清除成功"
#define AMSG_Param_Msg67                "清除脚本"
#define AMSG_Param_Msg68                "清除交易流水"
#define AMSG_Param_Msg69                "清除终端参数"
#define AMSG_Param_Msg70                "下载功能"
#define AMSG_Param_Msg73                "IC卡公钥下载"
#define AMSG_Param_Msg74                "IC卡参数下载"
#define AMSG_Param_Msg75                "终端业务控制参数"
#define AMSG_Param_Msg79                "是否支持免密?"
#define AMSG_Param_Msg80                "免密限额:"
#define AMSG_Param_Msg83                "是否支持免签?"
#define AMSG_Param_Msg84                "免签限额:"
#define AMSG_Param_Msg85                "是否支持CDCVM?"
#define AMSG_Param_Msg86                "是否支持电子签名?"
#define AMSG_Param_Msg87                "电子签名超时时间[S]:"
#define AMSG_Param_Msg91                "电子签名最大重签次数:"
#define AMSG_Param_Msg94                "电签是否打印签购单:"

///< trans_print.c
///< !------------------------------------------------------------
#define AMSG_Print_Printing             "正在打印"
#define AMSG_PrintEnd                   "打印结束"
#define AMSG_EnterKeyExit               "按[确认]退出"
#define AMSG_Print_EnterKeyReprint      "按[确认]重打"
#define AMSG_Print_EnterKeyContinue     "按[确认]继续"
#define AMSG_Print_PrintFormatErr       "打印格式错误"
#define AMSG_Print_MobileDeviceVerified "移动设备已验证用户，免密免签"
#define AMSG_Print_IsScanSale           "扫码交易,免签名"
#define AMSG_Print_IsEcTrade            "电子现金交易,无需签名"
#define AMSG_Print_NoPin                "交易金额未超%ld.%02ld元, 无需输密"
#define AMSG_Print_NoSignature          "交易金额未超%ld.%02ld元, 免签名"
#define AMSG_Print_NoPinAndNoSignature  "交易金额未超%ld.%02ld元, 免密免签"
#define AMSG_Print_Title                "银联POS签购单"
#define AMSG_Print_MerchantCopy         "商户存根(MERCHANT COPY)"
#define AMSG_Print_BankCopy             "银行存根(BANK COPY)"
#define AMSG_Print_CarcHolderCopy       "持卡人存根(CARD HOLDER COPY)"
#define AMSG_Print_MerchantName         "商户名称:"
#define AMSG_Print_MerchantNO           "商户编号: "
#define AMSG_Print_TerminalNo           "终端编号: "
#define AMSG_Print_Operator             "操作员号: "
#define AMSG_Print_ISS                  "发卡行:"
#define AMSG_Print_ACQ_Institute        "收单行:"
#define AMSG_Print_PaymentCode          "支付码号:"
#define AMSG_Print_CardNo               "卡号:"
#define AMSG_Print_TransType            "交易类型:"
#define AMSG_Print_ScanVoucherNo        "付款凭证号:"
#define AMSG_Print_VoucherNo            "凭证号:"
#define AMSG_Print_BatchNo              "批次号:"
#define AMSG_Print_ExpDate              "有效期:"
#define AMSG_Print_CardAssociation      "卡组织:"
#define AMSG_Print_AuthNo               "授权码:"
#define AMSG_Print_ReferNo              "参考号:"
#define AMSG_Print_TransDateTime        "日期/时间:"
#define AMSG_Print_TransAmount          "金额:   RMB"
#define AMSG_Print_Reference            "备 注:"
#define AMSG_Print_OldVoucher           "原凭证号:"
#define AMSG_Print_OldRefNo             "原参考号:"
#define AMSG_Print_OldAuthCode          "原预授权码:"
#define AMSG_Print_OldTransDateTime     "原交易日期:"
#define AMAG_Print_CardHolderSignature  "持卡人签名:"
#define AMSG_Print_I_Acknowledge        "本人确认以上交易, 同意将其记入本卡账户"
#define AMSG_Print_TXN_LIST             "交 易 明 细 单"
#define AMSG_Print_NeedAbortPrinting    "需要中止打印吗?"
#define AMSG_Print_EnterPrint           "按[确认]打印"
#define AMSG_Print_CancelPrint          "按[取消]退出"
#define AMSG_Print_CancelAbortPrinting  "按[取消]中止打印"
#define AMSG_Print_TotalExchange        "交 易 总 计 单"
#define AMSG_Print_Msg1                 "类型           笔数         金额"
#define AMSG_Print_Msg2                 "内卡数据"
#define AMSG_Print_Msg3                 "借记:"
#define AMSG_Print_Msg4                 "贷记:"
#define AMSG_Print_Msg5                 "外卡数据"
#define AMSG_Print_Msg6                 "结 算 总 计 单"
#define AMSG_Print_Msg7                 "交易时间:"
#define AMSG_Print_Msg8                 "内卡对账平"
#define AMSG_Print_Msg9                 "内卡对账不平"
#define AMSG_Print_Msg11                "消费:"
#define AMSG_Print_Msg14                "退货:"
#define AMSG_Print_Msg15                "外卡对账平"
#define AMSG_Print_Msg16                "外卡对账不平"
#define AMSG_Print_Msg17                "-- 测试/TEST --"
#define AMSG_Print_Msg18                "-- 重打印/DUPLICATED --"
#define AMSG_Print_Msg19                "凭证号 类型 卡号                金额      授权码"
#define AMSG_Print_Msg20                "S-消费 R-退货"

///< Bank Name
///< !------------------------------------------------------------
#define AMSG_Bank_CBC                   "建设银行"
#define AMSG_Bank_BCM                   "交通银行"
#define AMSG_Bank_BOC                   "中国银行"
#define AMSG_Bank_ABC                   "农业银行"
#define AMSG_Bank_CMB                   "招商银行"
#define AMSG_Bank_ICBC                  "工商银行"
#define AMSG_Bank_CIB                   "兴业银行"
#define AMSG_Bank_CEB                   "光大银行"
#define AMSG_Bank_CMBC                  "民生银行"
#define AMSG_Bank_SPDB                  "浦发银行"
#define AMSG_Bank_GDB                   "广发银行"
#define AMSG_Bank_BOB                   "北京银行"
#define AMSG_Bank_HXB                   "华夏银行"
#define AMSG_Bank_CITIC                 "中信银行"
#define AMSG_Bank_BJRCB                 "北京农商"
#define AMSG_Bank_SHRCB                 "上海农商"
#define AMSG_Bank_XHRCB                 "新会农商"
#define AMSG_Bank_GZRCB                 "广州农商"
#define AMSG_Bank_DGRCB                 "东莞农商"
#define AMSG_Bank_SDRCB                 "顺德农商"
#define AMSG_Bank_LZCCB                 "柳州商行"
#define AMSG_Bank_BKSH                  "上海银行"
#define AMSG_Bank_BKCS                  "长沙银行"
#define AMSG_Bank_BKDG                  "东莞银行"
#define AMSG_Bank_BKGZ                  "广州银行"
#define AMSG_Bank_GDNYB                 "南粤银行"
#define AMSG_Bank_PABC                  "平安银行"
#define AMSG_Bank_PSBC                  "邮储银行"
#define AMSG_Bank_CRB                   "华润银行"
#define AMSG_Bank_HRXJB                 "华融湘江"
#define AMSG_Bank_HXB2                  "华兴银行"
#define AMSG_Bank_GDRC                  "广东农信"
#define AMSG_Bank_ZSRC                  "中山农信"
#define AMSG_Bank_ZHRC                  "珠海农信"
#define AMSG_Bank_FSRC                  "佛山农信"
#define AMSG_Bank_ZQRC                  "肇庆农信"
#define AMSG_Bank_SSRC                  "三水农信"
#define AMSG_Bank_NHRC                  "南海农信"
#define AMSG_Bank_HNRC                  "湖南农信"
#define AMSG_Bank_UMS                   "银联商务"

