///< err: file err msg
///< !------------------------------------------------------------
#define AMSG_FileErr_FileUpdateFail             "update user data failed"
#define AMSG_FileErr_FileNotExist               "file not exist"
#define AMSG_FileErr_RecordNotFound             "record not found"
#define AMSG_FileErr_FileMoveFail               "remove file failed"
#define AMSG_FileErr_FileCloseFail              "close file failed"
#define AMSG_FileErr_DeleteRecordFail           "delete file data failed"
#define AMSG_FileErr_ReadFileFail               "read file failed"
#define AMSG_FileErr_WriteFileFail              "write file failed"
#define AMSG_FileErr_CreateFileFail             "create file failed"
#define AMSG_FileErr_OpenFileFail               "open file failed"
#define AMSG_FileErr_FileReadWriteErr           "file read-write error"

///< err: printer err msg
///< !------------------------------------------------------------
#define AMSG_PrinterErr_GetParamFail            "get printer param failed"
#define AMSG_PrinterErr_InitPrinterFail         "init printer failed"
#define AMSG_PrinterErr_SetParamFail            "set printer param failed"
#define AMSG_PrinterErr_ClearCacheFail          "clear printer cache failed"
#define AMSG_PrinterErr_CloseFail               "printer shutdown failed"
#define AMSG_PrinterErr_FeedFail                "paper feed error"
#define AMSG_PrinterErr_GetFontDataFail         "print failed"
#define AMSG_PrinterErr_GetBitmapDataFail       "print picture failed"
#define AMSG_PrinterErr_PrintTxtOver            "printing text beyond the limit"
#define AMSG_PrinterErr_PrintQRFail             "print barcode/qr code failed"
#define AMSG_PrinterErr_PrintFail               "printing failed"
#define AMSG_PrinterErr_NoPaper                 "paper out, plz put paper"
#define AMSG_PrinterErr_Overheat                "printer overheated, plz retry again later"
#define AMSG_PrinterErr_ParamError              "printer param error"
#define AMSG_PrinterErr_CommunicationError      "printer comms error"
#define AMSG_PrinterErr_NoPrinterModule         "no printer module"
#define AMSG_PrinterErr_LowBattery              "low battery, plz charge in time"
#define AMSG_PrinterErr_NotFontFile             "font file not exist"
#define AMSG_PrinterErr_CacheFull               "print cache full"
#define AMSG_PrinterErr_Printing                "printing"
#define AMSG_PrinterErr_PlzInstallBattery       "plz retry again after plug-in battery"
#define AMSG_PrinterErr_PrinterFailure          "printer failure, plz retry again"

///< err: cashier err msg
///< !------------------------------------------------------------
#define AMSG_CashierErr_DeleteNotAllow          "not allow delete"
#define AMSG_CashierErr_EnterPwdNotSame         "entered passwords differ"
#define AMSG_CashierErr_ChangeNotAllow          "not allow change"
#define AMSG_CashierErr_ChangeFail              "change failed"
#define AMSG_CashierErr_CashierIllegal          "cashier illegal"
#define AMSG_CashierErr_CashierFull             "cashier full"
#define AMSG_CashierErr_CashierNotExist         "cashier not exist"
#define AMSG_CashierErr_CashierExist            "cashier exist"
#define AMSG_CashierErr_OtherErr                "other error"

///< err:
///< !------------------------------------------------------------
#define AMSG_Err_End                            "Trade End"
#define AMSG_Err_Cancel                         "Cancel"
#define AMSG_Err_Timeout                        "Operation Timeout"
#define AMSG_Err_ParamErr                       "Parameter Error"
#define AMSG_Err_DriverErr                      "Driver Error"
#define AMSG_Err_MfDriverErr                    "RF Card Reader Fault"
#define AMSG_Err_IccDriverErr                   "IC Card Reader Fault"
#define AMSG_Err_ScanDriverErr                  "Scan Module Fault"
#define AMSG_Err_MagneticTrackDriverErr         "Track Reader Fault"
#define AMSG_Err_PrinterDriverErr               "Printer failure, plz retry again"
#define AMSG_Err_CommuErr                       "Commu Error"
#define AMSG_Err_ServerReturnErr                "Server Response Error"
#define AMSG_Err_CommuParamErr                  "Commu Param Error"
#define AMSG_Err_NetworkConnectFail             "Connection Host Failed"
#define AMSG_Err_DataSendFail                   "Send Data Failed"
#define AMSG_Err_DataReceiveFail                "Receive Data Failed"
#define AMSG_Err_KeyStoreFail                   "Storage Key Failed"
#define AMSG_Err_KeyDataErr                     "Storage Key Data Error"
#define AMSG_Err_EncryptionFail                 "Encryption Failed"
#define AMSG_Err_MACCheckErr                    "MAC Check Error"
#define AMSG_Err_CacheOverflow                  "Data Overflow"
#define AMSG_Err_InvalidData                    "Invalid Data"
#define AMSG_Err_LoadDataErr                    "Loading Data Failed"
#define AMSG_Err_ParsingDataErr                 "Parsed Data Failed"
#define AMSG_Err_AttestationErr                 "Verify Sign Failed"
#define AMSG_Err_NotLogon                       "Please Logon"
#define AMSG_Err_PleaseSettlement               "Please Settlement"
#define AMSG_Err_AdminNotTrade                  "Admin Not Trade, Plz Logon"
#define AMSG_Err_BatchMismatch                  "Batch Mismatch, Plz Logon"
#define AMSG_Err_WorkKeyErr                     "Key Error, Plz Logon"
#define AMSG_Err_TradeFull                      "Trade Full,Plz Settlement"
#define AMSG_Err_TradeEmpty                     "Empty Record"
#define AMSG_Err_OriginalTradeNotExist          "Original Trade Not Exist"
#define AMSG_Err_OriginalTradeVoid              "Original Trade Revoked/Unsupported"
#define AMSG_Err_LastTradeNotPrinted            "Last Trade Not Printed, Plz Reprint"
#define AMSG_Err_AmountOverlimit                "Amount Over Limit"
#define AMSG_Err_CardNOInconsistent             "Inconsistent Card By Refund"
#define AMSG_Err_WrongPassword                  "Password Error"
#define AMSG_Err_TradeHasBlocked                "Not Support Feature"
#define AMSG_Err_BitCheckErr                    "Field Check Error"
#define AMSG_Err_IllFormattedData               "Incorrect Format. Plz Reenter"
#define AMSG_Err_MsgTypeNotMatch                "Message Type Mismatch"
#define AMSG_Err_AmountNotMatch                 "Inconsistent Amount"
#define AMSG_Err_SerialNoNotMatch               "Inconsistent Serial NO"
#define AMSG_Err_TID_NotMatch                   "Inconsistent Terminal NO"
#define AMSG_Err_MID_NotMatch                   "Inconsistent Merchant NO"
#define AMSG_Err_IllFormattedSignatureData      "Wrong Signature, Plz Again"
#define AMSG_Err_KeyCheckErr                    "Key Check Error"
#define AMSG_Err_InsufficientStorageSpace       "Memory Full, Plz Settlement"
#define AMSG_Err_NotSettled                     "Terminal Not Settled"
#define AMSG_Err_UnknownErr                     "Unknown Error"

///< err: server error message
///< !------------------------------------------------------------
#define AMSG_HostErr_Approval                   "Approval"
#define AMSG_HostErr_ReferToIssuer              "Failure, Refer To Issuer"
#define AMSG_HostErr_InvalidCardNO              "Invalid Card NO"
#define AMSG_HostErr_InvalidMerchant            "Invalid Merchant"
#define AMSG_HostErr_Retry                      "Failure, Retry"
#define AMSG_HostErr_AmountExceedsLimit         "Amount Over Limit"
#define AMSG_HostErr_ExpiredCard                "Expired Card"
#define AMSG_HostErr_CardholderAuthenticationFailed   "Card holder verify Failed"
#define AMSG_HostErr_PartialApprovedAmount      "Partial Approved Amount"
#define AMSG_HostErr_Successful                 "Successful, VIP Customer"
#define AMSG_HostErr_InvalidTrade               "Invalid deal"
#define AMSG_HostErr_InvalidAmount              "Invalid Amount"
#define AMSG_HostErr_NoCardIssuer               "No Card Issuer"
#define AMSG_HostErr_CardNotInitialized         "Card Not Initialized/Sleep card"
#define AMSG_HostErr_IncorrectOperation         "Incorrect Operation"
#define AMSG_HostErr_NoOriginalDeal             "No Original Deal, Refer To Issuer"
#define AMSG_HostErr_PlzTryAgain                "Try Again"
#define AMSG_HostErr_CardNotAccepted            "Card Not Accepted"
#define AMSG_HostErr_CardSomethingWrong         "Card Something Wrong"
#define AMSG_HostErr_PlzUseChip                 "Plz Use Chip, Refer To Issuer"
#define AMSG_HostErr_InsufficientBalance        "Insufficient Balance"
#define AMSG_HostErr_IncorrectPIN               "Error Password"
#define AMSG_HostErr_BannedDeals                "Banned Deals"
#define AMSG_HostErr_CardCheckError             "Card Check Error"
#define AMSG_HostErr_AmountMismatch             "Amount Mismatch"
#define AMSG_HostErr_TradeNotSupported          "Trade Not Supported"
#define AMSG_HostErr_TakeLostCard               "Take Lost Card"
#define AMSG_HostErr_CheatCard                  "Cheat Card"
#define AMSG_HostErr_TakeStolenCard             "Take Stolen Card"
#define AMSG_HostErr_RestrictedCard             "Restricted Card"
#define AMSG_HostErr_SaleBeyondLimit            "Beyond limit of Sale"
#define AMSG_HostErr_ConfiscateCardContactAcquirer  "Pick-up, Refer Receiving Bank"
#define AMSG_HostErr_CardTradeNotAllowed        "Card Trade Not Allowed"
#define AMSG_HostErr_ConfiscateCard             "CARD RECYCLE"
#define AMSG_HostErr_TimeoutRetry               "Timeout, Retry"
#define AMSG_HostErr_ContactAcquirer            "Failure, Refer Receiving Bank"
#define AMSG_HostErr_PinRetryOver               "PIN Retry Over"
#define AMSG_HostErr_PlzLogon                   "Please Logon"
#define AMSG_HostErr_TransFail                  "Failure"
#define AMSG_HostErr_DuplicateBatch             "Re-upload offline data"
#define AMSG_HostErr_TryAgainLater              "Failure,try again later"
#define AMSG_HostErr_SystemBatch                "System Batch, try again later"
#define AMSG_HostErr_CardIssuingStateAnomaly    "Issuing Bank State Anomaly, try again later"
#define AMSG_HostErr_CardIssuingLineAnomaly     "Issuing Bank Line Anomaly, try again later"
#define AMSG_HostErr_RepeatDeal                 "deny, Repeat Deal, try again later"
#define AMSG_HostErr_SystemError                "deny, System Error"
#define AMSG_HostErr_CenterAnomaly              "deny, Center Anomaly, try again later"
#define AMSG_HostErr_InvalidTerminal            "Invalid Terminal"
#define AMSG_HostErr_CardIssuerTimeout          "Card Issuer Timeout"
#define AMSG_HostErr_IllFormattedPin            "IllFormatted PIN, Plz Logon"
#define AMSG_HostErr_MacError                   "Mac Error, Plz Logon"
#define AMSG_HostErr_TransferCurrencyNotAgree   "Transfer Currency Not Agree"
#define AMSG_HostErr_ToAccountBankIncorrect     "To Account Bank Incorrect"
#define AMSG_HostErr_ConfirmBankReceivedFunds   "Successful, Confirm Bank Received Funds"
#define AMSG_HostErr_SecurityHandlingFailed     "Security Handling Failed"
#define AMSG_HostErr_TradeError                 "Trade Error"

///< Message
///< !------------------------------------------------------------
#define AMSG_FuncParamErr               "Param Error"
#define AMSG_SetSuccess                 "SET OK"
#define AMSG_SetFailed                  "SET Failed"
#define AMSG_EnterToSet                 "[ O ]Continue"
#define AMSG_CancelToExit               "[ X ]Exit"
#define AMSG_QuerySuccess               "Query Success"
#define AMSG_DownloadSuccess            "Download Success"
#define AMSG_ChangeSuccess              "Updated Success"
#define AMSG_DelSuccess                 "Deleted Success"
#define AMSG_AddSuccess                 "Added Success"
#define AMSG_ResetSuccess               "Reset Success"
#define AMSG_EnterOrCancel              "[ O ]Enter  [ X ]Cancel"
#define AMSG_CancelExit                 "[ X ]Exit"
#if defined(QR200)
#define AMSG_PageTurn                   "[0/.]Page"
#else
#define AMSG_PageTurn                   "[¡ü¡ý]Page"
#endif
#define AMSG_EnterPowerOff              "1.Power Off"
#define AMSG_ClearReboot                "2.Restart"
#define AMSG_CancelBack                 "3.Exit"
#define AMSG_Rebooting                  "Resetting..."
#define AMSG_PowerOff                   "System Shutdown..."

///< title
///< !------------------------------------------------------------
#define AMSG_Title_Headline             "Unionpay"
#define AMSG_Title_Logon                "Logon"
#define AMSG_Title_Logoff               "Logoff"
#define AMSG_Title_Settlement           "Settlement"
#define AMSG_Title_LoadAID              "Download AID Param"
#define AMSG_Title_LoadCAPK             "Download CAPK Param"
#define AMSG_Title_LoadRF               "Download QPASS Param"
#define AMSG_Title_Reversal             "Reversal..."
#define AMSG_Title_Upload               "Uploading Script Results"
#define AMSG_Title_QueryBal             "Balance Enquiry "
#define AMSG_Title_Sale                 "Sale"
#define AMSG_Title_SaleVoid             "Void"
#define AMSG_Title_CardSaleVoid         "Bank Card Void"
#define AMSG_Title_ScanSaleVoid         "Scan Void"
#define AMSG_Title_Refund               "Refund"
#define AMSG_Title_CardRefund           "Bank Card Refund"
#define AMSG_Title_ScanRefund           "Scan Refund"
#define AMSG_Title_Print                "Print"
#define AMSG_Title_ReprintLastTrade     "Reprint Last Trade"
#define AMSG_Title_ReprintAnyTrade      "Reprint Any Trade"
#define AMSG_Title_PrintTradeDetail     "Print Trade Detail"
#define AMSG_Title_PrintTradeTotal      "Print Trade Total"
#define AMSG_Title_ReprintSettleSheet   "Reprint Settle Sheet"
#define AMSG_Title_Manage               "Manage"
#define AMSG_Title_TradeInquiries       "Trade Inquiry"
#define AMSG_Title_ViewTradeDetail      "View Trade Detail"
#define AMSG_Title_ViewTradeTotal       "View Trade Total"
#define AMSG_Title_VoucherNoSearch      "Search Detail by TraceNo"
#define AMSG_Title_CashiersManage       "Cashier Manage"
#define AMSG_Title_ChangeAdminPwd       "Change PWD"
#define AMSG_Title_CashierAdd           "Add Cashier"
#define AMSG_Title_CashierQuery         "Search Cashier"
#define AMSG_Title_CashierDel           "Del Cashier"
#define AMSG_Title_CashierChangePwd     "Change Cashier PWD"
#define AMSG_Title_PosLogon             "POS LOGON"
#define AMSG_Title_CashierLogon         "Cashier LOGON"
#define AMSG_Title_SysManage            "System Manage"

///< secretKey.c
///< !------------------------------------------------------------
#define AMSG_SetTMKIndex                "Set TMK Index"
#define AMSG_SecretKeyManage            "Secretkey Manage"
#define AMSG_DownloadTMK                "Download TMK"
#define AMSG_DownloadTMK_IC             "Download By IC Card"
#define AMSG_DownloadTMK_POS            "Download By Key POS"
#define AMSG_DownloadTMK_Manual         "Download By Input"
#define AMSG_SerialPortRecv             "[COM]Receive Waiting..."
#define AMSG_DownloadTMKSuccess         "TMK Download Success"
#define AMSG_DownloadTMKFail            "TMK Download Failed"
#define AMSG_USE_TMK_INDEX              "Use TMK Index(1-9):"
#define AMSG_SetSecretKeyType           "Set DES Algorithm"
#define AMSG_SecretKeySingle            "Single"
#define AMSG_SecretKeyDouble            "Double"
#define AMSG_SecretKeyDoubleTDK         "Double && TDK"
#define AMSG_PlzPushSecretKeyCard       "Insert Key Card"
#define AMSG_DontMoveSecretKeyCard      "Dont Move Key Card"
#define AMSG_SecretKeyCardReadFailed    "Read Key Card Failed"
#define AMSG_ManualSecretKey            "Download TMK(Manual)"
#define AMSG_InputTMKIndex              "Input TMK Index(1-9):"
#define AMSG_InputTMK                   "Input TMK(%dbit)"

///< elesign.c
///< !------------------------------------------------------------
#define AMSG_EsignInputSign             "sign in screen box"

///< cashier.c
///< !------------------------------------------------------------
#define AMSG_CashierSearch              "Search Operator"
#define AMSG_AddCashierNo               "Add Operator"
#define AMSG_DelCashierNo               "Del Operator"
#define AMSG_CashierNo                  "Cashier NO.:"
#define AMSG_ResetAdminPwd              "Reset Admin PWD"
#define AMSG_IsResetAdminPwd            "Reset Admin PWD?"
#define AMSG_ChangeSafePwd              "Change Safe PWD"
#define AMSG_ChangeManagePwd            "Change Manage PWD"
#define AMSG_ChangeAdminPwd             "Change Admin PWD"
#define AMSG_ChangeCashierNoPwd         "Change Operator PWD"
#define AMSG_InputCashierNo             "Input Operator No:"
#define AMSG_InputCashierNoPwd          "Input Operator PWD:"
#define AMSG_InputAdminPwd              "Input Admin PWD:"
#define AMSG_InputManagePwd             "Input Manage PWD:"
#define AMSG_InputSafePwd               "Input Safe PWD:"

#define AMSG_InputOldPwd                "Input Old PWD:"
#define AMSG_InputNewPwd                "Input New PWD:"
#define AMSG_InputAgain                 "Input Again:"

///< trans.c
///< !------------------------------------------------------------
#define AMSG_Success                    "Success"
#define AMSG_PlzConfirm                 "Please Confirm"
#define AMSG_Approval                   "Trade Success"
#define AMSG_Welcome                    "Welcome"
#define AMSG_NotLogon                   "Not Logon"
#define AMSG_InputAmount                "Input Amount:"
#define AMSG_ScanVoucherNo              "Scan Voucher No:"
#define AMSG_VoidSuccess                "Void Success"
#define AMSG_RefundSuccess              "Refund Success"
#define AMSG_SettlementSuccess          "Settlement Success"

///< trans_online.c
///< !------------------------------------------------------------
#define AMSG_ConnectingHost             "Host Connecting"
#define AMSG_HostConnected              "Host Connected"
#define AMSG_SendingData                "Data Sending"
#define AMSG_ReceivingData              "Data Receiving"
#define AMSG_Processing                 "Processing"
#define AMSG_PleaseWait                 "Waiting..."
#define AMSG_Received                   "Received"
#define AMSG_DownloadSearch             "Download Search"
#define AMSG_Downloading                "ownloading"
#define AMSG_DownloadEnd                "Download End"
#define AMSG_ReverseNumSend             "The %dth Send Reverse"
#define AMSG_ReverseSuccess             "Reverse Success"
#define AMSG_ReverseFailed              "Reverse Failed"
#define AMSG_ScriptSend                 "the %dth upload script"
#define AMSG_UploadSuccess              "Upload Success"
#define AMSG_UploadFailed               "Upload Failed"
#define AMSG_SettlementOK               "Settlement OK"
#define AMSG_SettlementUneven           "Settlement Uneven"
#define AMSG_SettlementFailed           "Settlement Failed"

///< trans_search.c
///< !------------------------------------------------------------
#define AMSG_TotalTransactions          "Total Amount"
#define AMSG_DebitInternalCard          "Debit:(Internal Card)"
#define AMSG_DebitForeignCard           "Debit:(Foreign Card)"
#define AMSG_CreditInternalCard         "Credit:(Internal Card)"
#define AMSG_CreditForeignCard          "Credit:(Foreign Card)"
#define AMSG_TickCount                  "%d"
#define AMSG_Amount                     "%ld.%02ld"

///< trans_ui.c
///< !------------------------------------------------------------
#define AMSG_InputErrClearKey           "Error Press[ < ]"
#define AMSG_ChangeIM                   "[ALPHA]Change IM"
#define AMSG_Warnings                   "Warning"
#define AMSG_BatteryLow                 "Low Battery"
#define AMSG_BatteryTooLow              "Too Low Battery, LetTrade"
#define AMSG_InCharge                   "Charging..."
#define AMSG_PlzConnectCharger          "Plz Connect Charger"
#define AMSG_PlzChargeInTime            "Plz charge in time, Press[ O ]Continue"
#define AMSG_PlzPlugInBattery           "Plz Plug-In Battery"
#define AMSG_PlzPulloutCard             "Plz Pullout Card"
#define AMSG_InputCardNo                "Input Card NO:"
#define AMSG_HandCardNo                 "Input"
#define AMSG_ScanCode                   "Scan"
#define AMSG_PlzAgain                   "Plz Again"
#define AMSG_ReadCardErr                "Read Card Error"
#define AMSG_Plz                        "Plz"
#define AMSG_SwipeCard                  "Swipe"
#define AMSG_PlugInCard                 "Insert"
#define AMSG_TapCard                    "Tap"
#define AMSG_ScanSale                   "Scan Sale"
#define AMSG_ScanSaleVoid               "Scan Void"
#define AMSG_ScanRefund                 "Scan Refund"
#define AMSG_Revoked                    "(Revoked)"
#define AMSG_InputOriginalSerialNo      "Input Original Voucher:"
#define AMSG_PreviousRecord             "[ O ]Last Record"
#define AMSG_Balance                    "Balance:"
#define AMSG_ClearManualInput           "Manual Input Press[ < ]"
#define AMSG_InputVoucherNo             "Input Voucher No:"
#define AMSG_InvalidDateFormat          "Invalid Date, input again"
#define AMSG_ConfirmAmount              "Confirm Amount:"
#define AMSG_CancelEdit                 "Press[ X ] Change"
#define AMSG_UI_Msg1                    "Amount: %ld.%02ld"

///< pos_param.c
///< !------------------------------------------------------------
#define AMSG_Param_Msg1                 "Set Merchant Param"
#define AMSG_Param_Msg2                 "Set Commu Param"
#define AMSG_Param_Msg3                 "Set Trans Param"
#define AMSG_Param_Msg4                 "TMK Manage"
#define AMSG_Param_Msg5                 "Set System Param"
#define AMSG_Param_Msg6                 "Password Manage"
#define AMSG_Param_Msg7                 "Set Other Param"
#define AMSG_Param_Msg8                 "Test Mode?"
#define AMSG_Param_Msg9                 "Set E-Signature Param"
#define AMSG_Param_Msg10                "1.ok%3s    0.nok%3s"
#define AMSG_Param_Msg11                "1.yes%3s    0.no%3s"
#define AMSG_Param_Msg12                "1.clear%3s    0.cancel%3s"
#define AMSG_Param_Msg13                "Terminal No.:"
#define AMSG_Param_Msg14                "Merchant No.:"
#define AMSG_Param_Msg15                "Merchant Name:"
#define AMSG_Param_Msg16                "Trans Number:"
#define AMSG_Param_Msg20                "Settle Prompt Print Detail?"
#define AMSG_Param_Msg23                "Void Use Card?"
#define AMSG_Param_Msg25                "Void Input PIN?"
#define AMSG_Param_Msg29                "Host1 IP:"
#define AMSG_Param_Msg30                "Host1 Port:"
#define AMSG_Param_Msg31                "Host1 Use SSL?"
#define AMSG_Param_Msg32                "Dial Retry:"
#define AMSG_Param_Msg33                "Receive Timeout:"
#define AMSG_Param_Msg35                "Balance Enquiry"
#define AMSG_Param_Msg36                "Sale"
#define AMSG_Param_Msg37                "Void"
#define AMSG_Param_Msg38                "Refund"
#define AMSG_Param_Msg44                "Other Param Set"
#define AMSG_Param_Msg45                "Void/Refund Input Admin PWD?"
#define AMSG_Param_Msg48                "Open EMV Log?"
#define AMSG_Param_Msg49                "Set Print Copy Count"
#define AMSG_Param_Msg50                "Print Copy Count(Copy)"
#define AMSG_Param_Msg51                "Set Maximum Trans"
#define AMSG_Param_Msg52                "Maximum Trans:"
#define AMSG_Param_Msg56                "message reposts"
#define AMSG_Param_Msg58                "Max Trans"
#define AMSG_Param_Msg59                "Set Other Param"
#define AMSG_Param_Msg61                "unsupported!"
#define AMSG_Param_Msg62                "Send Retry Count"
#define AMSG_Param_Msg63                "Retry Count:"
#define AMSG_Param_Msg64                "Clear Reversal Data"
#define AMSG_Param_Msg65                "In Clear..."
#define AMSG_Param_Msg66                "Clear SUCCESS"
#define AMSG_Param_Msg67                "Clear Script Data"
#define AMSG_Param_Msg68                "Clear Trans Data"
#define AMSG_Param_Msg69                "Clear Terminal Param"
#define AMSG_Param_Msg70                "Download Menu"
#define AMSG_Param_Msg73                "Download CAPK"
#define AMSG_Param_Msg74                "Download AID"
#define AMSG_Param_Msg75                "Terminal Control Param"
#define AMSG_Param_Msg79                "Support No PIN?"
#define AMSG_Param_Msg80                "No PIN Limit Amount:"
#define AMSG_Param_Msg83                "Support No Signature?"
#define AMSG_Param_Msg84                "No Signature Limit Amount:"
#define AMSG_Param_Msg85                "Support CDCVM?"
#define AMSG_Param_Msg86                "Support E-Signature?"
#define AMSG_Param_Msg87                "Timeout[S]:"
#define AMSG_Param_Msg91                "Maximum Retry Count:"
#define AMSG_Param_Msg94                "Print Trans Ticket?"

///< trans_print.c
///< !------------------------------------------------------------
#define AMSG_Print_Printing             "Printing"
#define AMSG_PrintEnd                   "Print End"
#define AMSG_EnterKeyExit               "Press[ O ]Exit"
#define AMSG_Print_EnterKeyReprint      "Press[ O ]Reprint"
#define AMSG_Print_EnterKeyContinue     "Press[ O ]Continue"
#define AMSG_Print_PrintFormatErr       "Print Format Error"
#define AMSG_Print_MobileDeviceVerified "Mobile device verified, no PIN and no signature"
#define AMSG_Print_IsScanSale           "Scan Sale, no signature"
#define AMSG_Print_IsEcTrade            "EC Trans, no signature"
#define AMSG_Print_NoPin                "Amount not exceeded %ld.%02ld RMB, no PIN"
#define AMSG_Print_NoSignature          "Amount not exceeded%ld.%02ld RMB, no signature"
#define AMSG_Print_NoPinAndNoSignature  "Amount not exceeded%ld.%02ld RMB, no PIN and no signature"
#define AMSG_Print_Title                "POS SALES SLIP"
#define AMSG_Print_MerchantCopy         "MERCHANT COPY"
#define AMSG_Print_BankCopy             "BANK COPY"
#define AMSG_Print_CarcHolderCopy       "CARD HOLDER COPY"
#define AMSG_Print_MerchantName         "MERCHANT NAME:"
#define AMSG_Print_MerchantNO           "MERCHANT NO.: "
#define AMSG_Print_TerminalNo           "TERMINAL NO.: "
#define AMSG_Print_Operator             "OPERATOR NO.: "
#define AMSG_Print_ISS                  "ISS NO.:"
#define AMSG_Print_ACQ_Institute        "ACQ NO.:"
#define AMSG_Print_PaymentCode          "PAYMENT CODE: "
#define AMSG_Print_CardNo               "CARD NO.:"
#define AMSG_Print_TransType            "TXN TYPE:"
#define AMSG_Print_ScanVoucherNo        "SCAN CODE:"
#define AMSG_Print_VoucherNo            "VOUCHER NO:."
#define AMSG_Print_BatchNo              "BATCH NO.:"
#define AMSG_Print_ExpDate              "EXP.DATE:"
#define AMSG_Print_CardAssociation      "ISS GROUP:"
#define AMSG_Print_AuthNo               "AUTH. NO.:"
#define AMSG_Print_ReferNo              "REF. NO.:"
#define AMSG_Print_TransDateTime        "DATE/TIME:"
#define AMSG_Print_TransAmount          "AMOUNT:   RMB"
#define AMSG_Print_Reference            "REFERENCE:"
#define AMSG_Print_OldVoucher           "OLD VOUCHER NO.:"
#define AMSG_Print_OldRefNo             "OLD REF. NO.:"
#define AMSG_Print_OldAuthCode          "OLD AUTH. NO.:"
#define AMSG_Print_OldTransDateTime     "OLD DATE/TIME:"
#define AMAG_Print_CardHolderSignature  "CARD HOLDER SIGNATURE:"
#define AMSG_Print_I_Acknowledge        "I ACKNOWLEDGE SATISFACTORY RECEIPT OF RELATIVE GOODS/SERVICE"
#define AMSG_Print_TXN_LIST             "TRANS DETAIL"
#define AMSG_Print_NeedAbortPrinting    "Need Abort Printing?"
#define AMSG_Print_EnterPrint           "Press[ O ]Print"
#define AMSG_Print_CancelPrint          "Press[ X ]Exit"
#define AMSG_Print_CancelAbortPrinting  "Press[ X ]Abort Printing"
#define AMSG_Print_TotalExchange        "TRANS SUMMARY"
#define AMSG_Print_Msg1                 "TYPE           SUM         AMOUNT"
#define AMSG_Print_Msg2                 "INTERNAL"
#define AMSG_Print_Msg3                 "DEBIT:"
#define AMSG_Print_Msg4                 "CREDIT:"
#define AMSG_Print_Msg5                 "FOREIGN"
#define AMSG_Print_Msg6                 "SETTLEMENT SUMMARY"
#define AMSG_Print_Msg7                 "DATE/TIME:"
#define AMSG_Print_Msg8                 "INTERNAL RECONCILIATION"
#define AMSG_Print_Msg9                 "INTERNAL RECONCILIATION UNEVEN"
#define AMSG_Print_Msg11                "SALE:"
#define AMSG_Print_Msg14                "REFUND:"
#define AMSG_Print_Msg15                "FOREIGN RECONCILIATION "
#define AMSG_Print_Msg16                "FOREIGN RECONCILIATION UNEVEN"
#define AMSG_Print_Msg17                "-- TEST --"
#define AMSG_Print_Msg18                "-- DUPLICATED --"
#define AMSG_Print_Msg19                "VOUCHER TYPE CARD NO            AMOUNT   AUTH NO"
#define AMSG_Print_Msg20                "S-SALE R-REFUND"

///< Bank Name
///< !------------------------------------------------------------
#define AMSG_Bank_CBC                   "CBC"
#define AMSG_Bank_BCM                   "BCM"
#define AMSG_Bank_BOC                   "BOC"
#define AMSG_Bank_ABC                   "ABC"
#define AMSG_Bank_CMB                   "CMB"
#define AMSG_Bank_ICBC                  "ICBC"
#define AMSG_Bank_CIB                   "CIB"
#define AMSG_Bank_CEB                   "CEB"
#define AMSG_Bank_CMBC                  "CMBC"
#define AMSG_Bank_SPDB                  "SPDB"
#define AMSG_Bank_GDB                   "GDB"
#define AMSG_Bank_BOB                   "BOB"
#define AMSG_Bank_HXB                   "HB"
#define AMSG_Bank_CITIC                 "CITIC"
#define AMSG_Bank_BJRCB                 "BJRCB"
#define AMSG_Bank_SHRCB                 "SHRCB"
#define AMSG_Bank_XHRCB                 "XHRCB"
#define AMSG_Bank_GZRCB                 "GZRCB"
#define AMSG_Bank_DGRCB                 "DGRCB"
#define AMSG_Bank_SDRCB                 "SDRCB"
#define AMSG_Bank_LZCCB                 "LZCCB"
#define AMSG_Bank_BKSH                  "BKSH"
#define AMSG_Bank_BKCS                  "BKCS"
#define AMSG_Bank_BKDG                  "BKDG"
#define AMSG_Bank_BKGZ                  "BKGZ"
#define AMSG_Bank_GDNYB                 "GDNYB"
#define AMSG_Bank_PABC                  "PABC"
#define AMSG_Bank_PSBC                  "PSBC"
#define AMSG_Bank_CRB                   "CRB"
#define AMSG_Bank_HRXJB                 "HRXJB"
#define AMSG_Bank_HXB2                  "HXB"
#define AMSG_Bank_GDRC                  "GDRC"
#define AMSG_Bank_ZSRC                  "ZSRC"
#define AMSG_Bank_ZHRC                  "ZHRC"
#define AMSG_Bank_FSRC                  "FSRC"
#define AMSG_Bank_ZQRC                  "ZQRC"
#define AMSG_Bank_SSRC                  "SSRC"
#define AMSG_Bank_NHRC                  "NHRC"
#define AMSG_Bank_HNRC                  "HNRC"
#define AMSG_Bank_UMS                   "UMS"

